//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceTestEntities : DbContext
    {
        public InsuranceTestEntities()
            : base("name=InsuranceTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<LOG_POLIZA_CLIENTE> LOG_POLIZA_CLIENTE { get; set; }
        public virtual DbSet<POLIZA> POLIZAs { get; set; }
        public virtual DbSet<TIPO_CUBRIMIENTO> TIPO_CUBRIMIENTO { get; set; }
        public virtual DbSet<TIPO_RIESGO> TIPO_RIESGO { get; set; }
    }
}
