//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_POLIZA_CLIENTE
    {
        public System.Guid ID_LPC { get; set; }
        public System.Guid ID_POL { get; set; }
        public System.Guid ID_CLI { get; set; }
        public System.DateTime FECHA_PROCESO { get; set; }
        public bool ACTIVA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual POLIZA POLIZA { get; set; }
    }
}
