//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIZA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POLIZA()
        {
            this.LOG_POLIZA_CLIENTE = new HashSet<LOG_POLIZA_CLIENTE>();
        }
    
        public System.Guid ID_POL { get; set; }
        public int ID_TIPO_CUBRIMIENTO { get; set; }
        public int ID_TIPO_RIESGO { get; set; }
        public long PRECIO { get; set; }
        public long PERIODO_COBERTURA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_POLIZA_CLIENTE> LOG_POLIZA_CLIENTE { get; set; }
        public virtual TIPO_CUBRIMIENTO TIPO_CUBRIMIENTO { get; set; }
        public virtual TIPO_RIESGO TIPO_RIESGO { get; set; }
    }
}
